[package]
name    = "rust-tui-template"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.27.0", features = ["serde", "event-stream"] }
ratatui   = { version = "0.26.0", features = ["serde", "macros"]}
anyhow    = "1.0.97"
